# Generated by Django 5.1.6 on 2025-02-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0002_alter_programphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='more_description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='poster_image',
        ),
        migrations.AlterField(
            model_name='moreprogramphoto',
            name='image',
            field=models.ImageField(upload_to='more_program_photos/'),
        ),
        migrations.AlterField(
            model_name='moreprogramphoto',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='more_program_photos', to='nss.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programphoto',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_photos', to='nss.program'),
        ),
    ]
