# Generated by Django 5.1.6 on 2025-02-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0003_remove_program_more_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
