# Generated by Django 5.1.6 on 2025-02-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0004_program_poster_image_alter_program_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='program_images/')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='more_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='programs', to='nss.programimage'),
        ),
        migrations.AddField(
            model_name='program',
            name='more_images',
            field=models.ManyToManyField(blank=True, related_name='more_programs', to='nss.programimage'),
        ),
    ]
