# Generated by Django 5.1.6 on 2025-02-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0007_delete_photo_alter_moreprogramphoto_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='images',
        ),
        migrations.RemoveField(
            model_name='program',
            name='more_images',
        ),
        migrations.DeleteModel(
            name='ProgramImage',
        ),
    ]
